name: NPM Publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - run: npm run build --if-present

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Check if version exists
      id: version-check
      run: |
        PACKAGE_VERSION=$(node -p "require('./package.json').version")
        echo "Package version: $PACKAGE_VERSION"
        if npm view object-deep-compare@$PACKAGE_VERSION version &> /dev/null; then
          echo "Version $PACKAGE_VERSION already exists in the registry, skipping publish"
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "Version $PACKAGE_VERSION does not exist in the registry, will publish"
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
    - name: Publish to NPM
      if: steps.version-check.outputs.exists != 'true'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
